name: test-environment
channels:
  - conda-forge
dependencies:
  - dask-core
  - python-duckdb
  - pandas
  - polars
  - pyarrow >=15
  - numpy
  - pytest
  - pytest-cov
  - numba
  - awkward
  - distributed
  - pip
  - ray-data
  - pip:
      - git+https://github.com/dask-contrib/dask-awkward
