name: test-environment
channels:
  - conda-forge
dependencies:
  - pandas
  - polars
  - dask >=2025
  - pyarrow >=17
  - numpy >=2
  - pytest
  - pytest-cov
  - numba
  - awkward
  - distributed
  - openjdk ==20
  - pyspark
  - pip
  - pip:
      - git+https://github.com/dask-contrib/dask-awkward
