name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - pandas
  - polars
  - dask
  - pyarrow
  - pytest
  - pytest-cov
  - numba
  - dask-awkward
  - distributed
  - openjdk ==20
  - pyspark
  - pip:
      - git+https://github.com/dask-contrib/dask-awkward
