name: test-environment
channels:
  - conda-forge
dependencies:
  - dask >=2025
  - pandas
  - polars
  - pyarrow >=15
  - numpy
  - pytest
  - pytest-cov
  - numba
  - awkward
  - distributed
  - pip
  - pip:
      - ray[data]
      - git+https://github.com/dask-contrib/dask-awkward
