name: PyPI Tests

on:
  push:
    branches: ['main']
    paths-ignore: ['**.md', 'docs/**']
  pull_request:
    paths-ignore: ['**.md', 'docs/**']
  workflow_dispatch:

concurrency:
  group: 'pypi-tests-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{matrix.platform}}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Conda Environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: .github/envs/environment.yml
        activate-environment: test-environment
    - name: install
      shell: bash -l {0}
      run: |
        pip install pip wheel -U
        pip install -q --no-cache-dir -e .[test]
        pip list
    - name: test
      shell: bash -l {0}
      run: |
        python -m pytest -v --cov-config=.coveragerc --cov akimbo
